spring:
  application:
    name: ejercicio-hexagonal
  datasource:
    url: jdbc:postgresql://localhost:5432/carrito-compras
    username: postgres
    password: secret

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    session:
      timeout: 21600s